### ISSUE TITLE
导入开发者工具后没有显示界面

### ISSUE THREAD

**Issue by Lu-Tan** [lxljl/sea-ai#1]
您好，我按照您的readme先安装了依赖并添加了实时编译，但是在开发者工具中导入项目时并没有出现显示界面，也没有找到您的wsml文件。请问主界面在哪里鸭？谢谢你啦

**Comment by lxljl** [comment]
使用wepy编译，编译后的文件默认dist目录中

**Comment by Lu-Tan** [comment]
谢谢！！！
